arch = [
    "hyprland",
    "brightnessctl",
    "rofi",
    "hypridle",
    "hyprlock",
    "hyprshot",             # screenshot
    "wf-recorder", "slurp", # gif recording
    "noctalia-shell-git", "matugen-bin", "cava", "cliphist"#, "xdg-desktop-portal"
]