arch = [
    "qt6-wayland",
    "libplasma",
    "plasma-desktop", "xdg-user-dirs",
    "plasma-firewall",
    "plasma-integration",
    "plasma-nm", "modemmanager", "usb_modeswitch",
    "plasma-pa",
    "plasma-systemmonitor",
    "plasma-thunderbolt",
    "plasma-workspace", "accountsservice",
    "xdg-desktop-portal-kde",

    "bluedevil",
    "powerdevil",
    "breeze-gtk",
    "dolphin", "ffmpegthumbs",
    "kde-gtk-config",
    "kdegraphics-thumbnailers",
    "kdeplasma-addons",
    "kdialog",
    "kinfocenter", "dmidecode",
    "kio-admin",
    "kscreen",
    "kwallet-pam",
    "kwalletmanager",
    "phonon-qt6-mpv",
    "xorg-server",
    "xorg-xdpyinfo",
    "xorg-xinit",
    "xorg-xinput",
    "xorg-xkill",
    "xorg-xrandr",
    "xsettingsd",

    "noto-color-emoji-fontconfig",
    "noto-fonts",
    "noto-fonts-cjk",
    "noto-fonts-emoji",
]